Fix e2e-upgrade-kind.sh to get onlye one endpoint IP
Today kind upgrade test started failing due to the following error.

https://github.com/knative-sandbox/net-kourier/pull/469/checks?check_run_id=2091315954
```
    probe_test.go:56: ingressendpoint: "172.18.0.3 172.18.0.2"
    util.go:970: Error making GET request: Get "http://probe-ailwbgxo.example.com": dial tcp: lookup 172.18.0.3 172.18.0.2: no such host
```

It seems the endpoint IP was specified by `"172.18.0.3 172.18.0.2"`.

This patch fixes it by correcting the IP by the same way with other kind-e2e.yaml.